version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (io.Closer).Close
        - (io.ReadCloser).Close
        - (*text/tabwriter.Writer).Flush
        - os.Setenv
        - os.Unsetenv
